### ISSUE TITLE
Converge plugin codes to https://github.com/elpaso/qgis-ipythonconsole

### ISSUE THREAD

**Issue by luipir** [Sharpie/qgis-ipython#6]
make sense to converge dev efforts in a single plugin?
AFAIK there is an active and working one:
https://github.com/elpaso/qgis-ipythonconsole

It would make sense to collaborate on that. Any opinion?

regards

**Comment by Sharpie** [comment]
My line of work has taken me out of the GIS field, so there isn't any ongoing effort in this project to converge. If there are bits of code here that folks find useful, I'd be more than happy if someone picked this project up and either maintained it as an active fork or extracted bits and contributed them to other active projects.

**Comment by luipir** [comment]
tnx
